### ISSUE TITLE
JSON file icon is not getting applied

### ISSUE THREAD

**Issue by gj1118** [oivva/st-file-icons#12]
#### Expected Behavior
The file icon for JSON should be displayed
#### Current Behavior
A generic "gear" icon is displayed for JSON files. 

![image](https://cloud.githubusercontent.com/assets/473101/19572575/cead3b30-96d0-11e6-9e1b-c6fe8facb5a4.png)

![image](https://cloud.githubusercontent.com/assets/473101/19572700/6600bf02-96d1-11e6-86de-e8c8b3950d41.png)

#### Steps to Reproduce (for bugs)
1. Download and extract the zip file
2. Copy it to the packages folder - (Preferences -> Browse Packages)
3. Restart Sublime text

#### Context
I was trying to open JSON setting file and realized that the JSON icon was not getting applied to the JSON file.

#### Your Environment

- File Icons: 1.0.2
- Sublime Text: 3125
- Platform: windows
- Package Control: False
- Current Theme: SoDaReloaded Light.sublime-theme
- Installed Themes: {'dark': ['SoDaReloaded Dark.sublime-theme'], 'solarized_dark': ['SodaReloaded Solarized Dark.sublime-theme'], 'solarized_light': ['SodaReloaded Solarized Light.sublime-theme'], 'light': ['SoDaReloaded Light.sublime-theme'], 'Theme - Default': ['Default.sublime-theme']}

#### Console output
DPI scale: 1
startup, version: 3125 windows x64 channel: dev
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/sublime Text 3
packages path: /C/Users/<user>/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/<user>/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/<user>/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.268313
startup time: 0.386313
first paint time: 0.389313
first paint time: 0.391313
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin ColorSchemeSelector.ColorSchemeSelector
reloading plugin Open Folder.OpenFolder
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin Select Quoted.select_quotes
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Themr.themr
reloading plugin TortoiseSVN.TortoiseSVN
reloading plugin Zen Tabs.TabsWorker
reloading plugin Zen Tabs.ZenTabs
reloading plugin Zen Tabs.ZenTabsTest
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin Terminal.Terminal
reloading plugin zz File Icons.zz File Icons
plugins loaded

***
File Icons: Initializing
File Icons: Getting the settings
        >>> {'color_on_hover': '', 'force_override': True, 'color': '', 'color_on_select': '', 'opacity_on_hover': 0.5, 'size': 8, 'opacity': 0.75, 'opacity_on_select': 1.0}
File Icons: Activating the icons
File Icons: Getting colors of the icons
File Icons: Getting installed themes
        >>> {'Theme - Default': ['Default.sublime-theme'], 'solarized_dark': ['SodaReloaded Solarized Dark.sublime-theme'], 'light': ['SoDaReloaded Light.sublime-theme'], 'solarized_light': ['SodaReloaded Solarized Light.sublime-theme'], 'dark': ['SoDaReloaded Dark.sublime-theme']}
File Icons: Getting supported themes
        >>> {}
File Icons: The multi color mode is already activated
File Icons: Themes are already patched
File Icons: Finished
***

Limit: 100
Full path: False
Highlight: True
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2016-10-20 13:56:41, next run at 2016-10-20 14:56:41 or after

**Comment by gj1118** [comment]
Ok .. I had to install the boxy theme to use it with my theme. Now its working fine. 
![image](https://cloud.githubusercontent.com/assets/473101/19573222/50394318-96d3-11e6-88e2-e507855831f4.png)

Can you please provide a list of steps on how to use it independently of the Boxy theme ?  

Thanks so much .. 
With Regards
Gagan

**Comment by oivva** [comment]
@gj1118 You don't need to install `Boxy Theme`, because starting next release I'll remove all preferences from it. You have this problem because of icon preferences conflict, (see [this](https://github.com/Miw0/SoDaReloaded-Theme/blob/master/settings/prefs/icon_json.tmPreferences)).

You can request [support for this package](https://github.com/oivva/st-file-icons#bring-support-to-your-theme) from the developer of the `Theme - SoDaReloaded`.
