### ISSUE TITLE
Add an icon for .config files

### ISSUE THREAD

**Issue by gj1118** [oivva/st-file-icons#14]
.config files are basically XML files used for storing application settings. As of now, there isn't an icon for the .config files. Can you please add an icon for .config files ?

![image](https://cloud.githubusercontent.com/assets/473101/19655528/4fea52a2-99ea-11e6-91df-475bd9e40884.png)

Expected Behaviour 
For all the .config files , a .config icon should be displayed. 

Actual Behaviour
Default icon is displayed for the .config file. Please see the above snapshot for more information.

**Comment by r3nya** [comment]
@oivva please assign to me.

**Comment by r3nya** [comment]
Hey @gj1118 and @oivva!
Do you like http://www.flaticon.com/free-icon/settings_109596 icon for `.config` files?

**Comment by oivva** [comment]
We already have [gear icon](https://github.com/oivva/st-file-icons/blob/dev/dist/zpatches/icons/file_type_settings.png).

```js
  "file_type_settings": {
    "color": "graphite",
    "syntaxes": [
      {
        "name": "INI",
        "scope": "source.ini"
      }
    ],
    "aliases": [
      {
        "name": "JSON (Settings)",
        "extensions": [
          "jsbeautifyrc"
        ],
        "base": "source.json",
        "scope": "source.json.settings"
      }
    ]
  },
```

Just create xml alias for it.

**Comment by r3nya** [comment]
@oivva understood. Thanks!
