### ISSUE TITLE
Installed through PC but doesn't works

### ISSUE THREAD

**Issue by equinusocio** [oivva/st-file-icons#16]
I've Installed this package through Package Control but it doesn't works. [5852](https://github.com/wbond/package_control_channel/pull/5852) was merged, please release the 2.0.0 :)

**Comment by oivva** [comment]
I'll release it today, just a little bit later. Sorry for the inconvenience!

**Comment by equinusocio** [comment]
No problem. 👍🏻

**Comment by oivva** [comment]
I've published the 2.0.0 release. It will be available soon via Package Control.
