### ISSUE TITLE
Add an icon for source map files

### ISSUE THREAD

**Issue by gj1118** [oivva/st-file-icons#17]
can you please add an icon for .map file type ? 

![image](https://cloud.githubusercontent.com/assets/473101/19832284/beb6062a-9ded-11e6-915f-dea58103e0fa.png)

Right now the default icon is displayed.

**Comment by oivva** [comment]
Please vote for it :+1: :-1:

**Comment by infantito** [comment]
source.css.map

**Comment by oivva** [comment]
>source.css.map

? :smile:

**Comment by infantito** [comment]
I wanted to say the following: :cambodia: 
![style css map](https://cloud.githubusercontent.com/assets/9045302/20141778/de0ed6d0-a65f-11e6-88f9-ecc8bdf81acb.png)

**Comment by oivva** [comment]
Agree, it's better to use default syntaxes than aliases to them :+1:

**Comment by oivva** [comment]
Ok, there is no need in map icon, just open it as JSON file.

**Comment by oivva** [comment]
We are always trying to minimize the aliases abuse.
