### ISSUE TITLE
Add an icon for NSIS files

### ISSUE THREAD

**Issue by idleberg** [oivva/st-file-icons#18]
We in preparation to roll out the new icon for NSIS and as a user of your package, I would love to see support for NSIS scripts.

Extensions: nsh, nsi
Icon: https://github.com/idleberg/nsis-logo-v3/blob/master/src/Logo/below%2048x48/mono-flat.svg
Suggested color: #867991 (134,121,145)

Let me know if you need anything else!

**Comment by r3nya** [comment]
@oivva can I help you?

**Comment by oivva** [comment]
In Progress, see https://github.com/oivva/st-file-icons/projects/1 :smile: 

You can add one of the `Planned` icons :wink:

**Comment by r3nya** [comment]
@oivva ah … Ok! :)
