### ISSUE TITLE
ZZ file Icons 2.0.0 - JSON file is broken

### ISSUE THREAD

**Issue by gj1118** [oivva/st-file-icons#20]
hi, 
I am using the Boxy(v 5.0.0) Monokai theme and Package control updated ZZ file icons to the latest version today (2.0.0). However, it seems that the JSON file is broken. 

![image](https://cloud.githubusercontent.com/assets/473101/19912896/40ee485e-a074-11e6-8664-e0525ef1a1ec.png)

I have restarted ST multiple times, run it as an administrator, cleared the cache and the session folder , but none of it is working. Is this a problem on my machine only, or is this a bug?  

Please confirm. 

Thanks

**Comment by oivva** [comment]
Please provide output of the `File Icons: Environment`. I think your issue related to other theme that doesn't support this package, in this case you have to remove it or request support for this package from the theme's developer.

**Comment by gj1118** [comment]
thanks... you are right. Problem was in the other theme. I am marking this as resolved.
