### ISSUE TITLE
Syntax definition conflicts with PackageDev

### ISSUE THREAD

**Issue by FichteFoll** [oivva/st-file-icons#21]
This package provides `dist/languages/JSON (Sublime).tmLanguage`, a syntax definition for JSON files that configure aspects of Sublime Text. Unfortunately, this conflicts with the PackageDev package, which also defines syntax definitions for many configuration files.

Additionally (and even more severe), this syntax definition defines the base scope `source.json, source.json.sublime`, which makes the scope selector `source source` match and causes the entire file to be rendered in dimmed color for me (for embedded languages). Instead, just use `source.json.sublime`.

**Comment by FichteFoll** [comment]
The PackageDev package can be found here: https://github.com/SublimeText/PackageDev/

I'm currently working on re-writing the syntax definitions in the new format and adding highlighting for `.sublime-syntax`.

**Comment by oivva** [comment]
@FichteFoll Ah, thanks a lot! 

>  Instead, just use source.json.sublime

I'll fix this.

Also I should remove the language or only the stuff from `dist\extenstions`, so the user will be able to set this syntax manually?

**Comment by FichteFoll** [comment]
Yes, remove all `dist/extensions` files. The fileTypes property of tmLanguage files should be enough for this and is more easily configured by the user, whereas there have been several complaints about themes forcing their special syntaxes upon users.

**Comment by oivva** [comment]
@FichteFoll I'll release 2.0.1 with fix today. Thanks a lot for clarification.
