### ISSUE TITLE
Nginx icon

### ISSUE THREAD

**Issue by r3nya** [oivva/st-file-icons#33]
Svg: https://github.com/Alhadis/FileIcons/blob/master/svg/nginx.svg
Syntax: https://github.com/brandonwamboldt/sublime-nginx/blob/master/Syntaxes/nginx.tmLanguage
Scope: `source.nginx`

**Comment by oivva** [comment]
Also don't forget to update [PACKAGES.md][PACKAGES.md] for users and [MIGRATION.md][MIGRATION.md] for theme developers. E.g. see fadabfe0e.

**Comment by r3nya** [comment]
@oivva good point. I will update this files too.
