### ISSUE TITLE
Icon for Flow

### ISSUE THREAD

**Issue by r3nya** [oivva/st-file-icons#36]
Subj: https://flowtype.org/
SVG icon: https://github.com/Alhadis/FileIcons/blob/master/svg/Flow.svg
File to handle: `.flowconfig`

**Comment by oivva** [comment]
As I can see `.flowconfig` ini syntax? However we can't create aliases for community packages, because user may not have theme installed. So I think the situation is pretty the same to #37

**Comment by r3nya** [comment]
Yeah … I though about it, and now I think so.

**Comment by ihodev** [comment]
It seems that's possible. lt will be fixed in #104 .
