### ISSUE TITLE
Gear icon for Buck

### ISSUE THREAD

**Issue by r3nya** [oivva/st-file-icons#37]
Subj: https://buckbuild.com/concept/buckconfig.html
Need to show default buck icon for `.buckconfig`, base scope `text.plain`.

**Comment by oivva** [comment]
Nope :) 

> This file uses the INI file formatwith a few extensions discussed below.

User can do next `View -> Syntax -> Open all with ... -> EditorConfig -> INI` or other package which contains INI syntax, also that syntax can provide this extension by default.

**Comment by oivva** [comment]
It's better to add this extension to the https://github.com/clintberry/sublime-text-2-ini

**Comment by r3nya** [comment]
@oivva good idea. :)
