### ISSUE TITLE
Unable to find package via Package Control

### ISSUE THREAD

**Issue by verpixelt** [oivva/st-file-icons#4]
Running Sublime Text Build 3126 on Mac OS 10.12 and I'm unable to find your package via Package Control.

**Comment by equinusocio** [comment]
The package is under review by the package control team, we have to wait.

**Comment by verpixelt** [comment]
Thanks for the feedback!

**Comment by oivva** [comment]
I've published the 2.0.0 release. It will be available soon via Package Control.
