### ISSUE TITLE
Issues by Ruby developers

### ISSUE THREAD

**Issue by r3nya** [oivva/st-file-icons#41]
So … I asked my friends to test it, and I got a lot of issues.

Need to add or try to add some icons for this files:

* [x] .htaccess via [Apache​Conf.tm​Language](https://packagecontrol.io/packages/ApacheConf.tmLanguage)
* [x] .ruby-version
* [x] .ruby-gemset
* [x] .rvmrc
* [x] .rspec
* [x] .node-version
* [x] .nvmrc
* [x] Gemfile.lock (Gemfile exists)
* [x] Appfile (Fastfile exists) - just associate this file with Ruby syntax: `View -> Syntax -> Open all with current extension as ... -> Ruby`)
* [x] gulpfile.coffee (gulpfile.js exists)
* [x] .woff2 (.woff exists)
* [x] .mst will be available via [Handlebars](https://github.com/daaain/Handlebars) or [SublimeHTMLMustache](https://github.com/adamchainz/SublimeHTMLMustache)
* [ ] .plist
* [x] composer.json
* [x] composer.lock

And I got bad feedback about Heroku logo on `Procfile` file.

I will try to fix some issues on current iteration but maybe I can't fix all of them. And @oivva you can help me. :)

**Comment by skalfyfan** [comment]
@r3nya @oivva +++ Agree with this and have the same issue with Ruby projects. Many missing ruby icons for ruby related file types.

I'm not very experienced with Sublime packaging and development. Is it fairly easy to update and/or add icon support for different file types like those listed here? Would either of you be able to point me where I'd go and edit to add or associate a _filename_ or extension with a file type?

I noticed this great package added an icon for the _.dockerignore_ file! 👍 So I assume this would be all possible to edit locally? Thanks!

**Comment by oivva** [comment]
@skalfyfan Please post your requests I'll try to add as much as possible :wink:

**Comment by oivva** [comment]
> I assume this would be all possible to edit and add locally, as long as the correct package is installed for the file type? Thanks!

Yes, of course. However I have plans to add alias support to some community packages, so you don't need to do this manually. In any case if next update won't resolve your issues, I'll explain how to resolve them manually.

**Comment by r3nya** [comment]
@oivva hooray! 🤓

**Comment by r3nya** [comment]
Created PR for SublimeHTMLMustache
https://github.com/adamchainz/SublimeHTMLMustache/pull/13
