### ISSUE TITLE
Provide `server.js` icon (a server or nodejs)

### ISSUE THREAD

**Issue by oivva** [oivva/st-file-icons#7]
It would be good `server.js` files have the icon of a server or nodejs. This request is from #6. Please vote for it :wink: :+1: :-1:

**Comment by equinusocio** [comment]
I think that a `server.js` can be any type of file (not only node.js or a server related file). I can name `server.js` a file full of functions, not related to the server environment, or a file related to my openshift machine, so i think a common js icon should be more appropriate than a specific one.
