### ISSUE TITLE
Add an icon for webpack (webpack.config)

### ISSUE THREAD

**Issue by oivva** [oivva/st-file-icons#8]
#### Expected Behavior

webpack.config.js

![react](https://cloud.githubusercontent.com/assets/9801624/19408465/4b8fe3dc-92c6-11e6-8be8-97041b72422f.png) or ![webpack](https://cloud.githubusercontent.com/assets/9801624/19408466/4b91f7c6-92c6-11e6-9120-2d04de185778.png)
#### Current Behavior

Currently we have default icon: ![file_type_default](https://raw.githubusercontent.com/oivva/zz-file-icons/dev/dist/zpatches/icons/file_type_default.png)
#### Possible Solution

Create syntax alias to the default js syntax.

**Comment by infantito** [comment]
https://cloud.githubusercontent.com/assets/9801624/19408466/4b91f7c6-92c6-11e6-9120-2d04de185778.png

**Comment by infantito** [comment]
![webpack](https://cloud.githubusercontent.com/assets/9045302/19441128/26818dcc-944a-11e6-886e-01c76dea78b7.png)

Psd: "This, because seti_ui has the other icon to REACT - JSX"

**Comment by r3nya** [comment]
Need to use icon 2.
